---
dataset: TREC6
classifier: Bert
computer: labo
split: 20
dataset_size: 10
algo: ChatGPTDescription
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 50
batch_size_classifier: 32

tokenizer: "tweetTokenizer"
fix_dataset: False