---
dataset: TREC6
classifier: Bert
computer: labo
split: 1
dataset_size: 0
algo: CBERT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 5
batch_size_classifier: 32

nb_epoch_algo: 2 #5
learning_rate: 0.00005
batch_size_algo: 16
tokenizer: "tweetTokenizer"
prob_reg: 0.5

fix_dataset: False