---
dataset: FakeNews
classifier: bertAEDA
computer: labo
split: 0
dataset_size: 500
algo: AEDA
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 30
prob_reg: 0.5

batch_size_classifier: 32
tokenizer: "tweetTokenizer"

fix_dataset: False