---
dataset: Irony
classifier: Bert
computer: labo
split: 10
dataset_size: 50
algo: EDA
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 15
batch_size_classifier: 32

tokenizer: "tweetTokenizer"
alpha_sr: 0.1
alpha_ri: 0.1
alpha_rs: 0.1
alpha_rd: 0.1

fix_dataset: False