---
dataset: TREC6
classifier: Bert
computer: labo
split: 10
dataset_size: 20
algo: CBERT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 45

batch_size_classifier: 32
tokenizer: "tweetTokenizer"

nb_epoch_algo: 10
learning_rate: 0.00005

batch_size_algo: 4
batch_size_generation: 4

fix_dataset: False