---
dataset: SST2
classifier: bertAEDA #Bert
computer: labo
split: 0
dataset_size: 1000
algo: AEDA
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 10 #5
batch_size_classifier: 32

prob_reg: 0.5

tokenizer: "tweetTokenizer"