---
dataset: FakeNews
classifier: Bert
computer: labo
split: 1
dataset_size: 2000
algo: T5ParQuora
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 8
batch_size_classifier: 32
tokenizer: "tweetTokenizer"
