---
dataset: FakeNews
classifier: Bert
computer: labo
split: 10
dataset_size: 50
algo: T5ParQuora
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 20
batch_size_classifier: 32
tokenizer: "tweetTokenizer"
