---
dataset: IronyB
classifier: Bert
computer: labo
split: 1
dataset_size: 1000
algo: BART
random_seed: 7
selector: random
max_seq_length: 16
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 35
batch_size_classifier: 32
tokenizer: "tweetTokenizer"
fix_dataset: False

batch_size_algo: 4
nb_epoch_algo: 3
learning_rate: 0.0005
batch_size_generation: 4