---
dataset: IronyB
classifier: Bert
computer: labo
split: 0
dataset_size: 1000
algo: dummy
random_seed: 7
selector: random
meta_strategy: dummy
max_seq_length: 0
one_shot: False
nb_epoch_classifier: 35


batch_size_classifier: 32
tokenizer: "tweetTokenizer"
fix_dataset: False