---
dataset: Irony
classifier: Bert
computer: labo
split: 0
dataset_size: 1500
algo: dummy
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 20

batch_size_classifier: 32
fix_dataset: False
tokenizer: tweetTokenizer