---
dataset: IronyB
classifier: Bert
computer: labo
split: 10
dataset_size: 50
algo: BART
random_seed: 7
selector: random
max_seq_length: 16
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 30

batch_size_classifier: 32
tokenizer: "tweetTokenizer"

batch_size_algo: 4
nb_epoch_algo: 3
learning_rate: 0.0005
batch_size_generation: 4

fix_dataset: False