---
dataset: IronyB
classifier: Bert
computer: labo
split: 10
dataset_size: 50
algo: CBERT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 30

batch_size_classifier: 32
tokenizer: "tweetTokenizer"

fix_dataset: False
nb_epoch_algo: 2 #5
learning_rate: 0.00005
batch_size_algo: 16