---
dataset: IronyB
classifier: Bert
computer: labo
split: 10
dataset_size: 50
algo: T5BT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 35
batch_size_classifier: 32
batch_size_generation: 8
batch_size_algo: 8
num_epoch_algo: 4

tokenizer: "tweetTokenizer"
fix_dataset: False