---
dataset: SST2
classifier: Bert
computer: labo
split: 10
dataset_size: 10
algo: CVAE
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 10

hidden_size_algo: 1024
word_dropout: 0.5
dropout_algo: 0.5
latent_size: 10
embeddings: None
freeze_embeddings: False
tie_embeddings: False
tie_encoders: False
nb_epoch_algo: 30
x0: 15
sampling_strategy: random

batch_size_classifier: 32
fix_dataset: False
tokenizer: "tweetTokenizer"