---
dataset: IronyB
classifier: Bert
computer: labo
split: 1
dataset_size: 0
algo: CBERT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 15
batch_size_classifier: 32

nb_epoch_algo: 4
learning_rate: 0.00005
batch_size_algo: 16

tokenizer: "tweetTokenizer"
fix_dataset: False