---
dataset: Irony
classifier: Bert
computer: labo
split: 1
dataset_size: 2000
algo: T5Par
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 10

batch_size_classifier: 32
tokenizer: "tweetTokenizer"