---
dataset: SST2
classifier: Bert
computer: labo
split: 10
dataset_size: 10
algo: CBERT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 10
batch_size_classifier: 32

tokenizer: "tweetTokenizer"

fix_dataset: True

nb_epoch_algo: 10
learning_rate: 0.00005
batch_size_algo: 16