---
dataset: Irony
classifier: Bert
computer: labo
split: 0
dataset_size: 10
algo: dummy
random_seed: 7
selector: random
max_seq_length: 0
one_shot: False
nb_epoch_classifier: 10
meta_strategy: dummy

batch_size_classifier: 32
tokenizer: "tweetTokenizer"