---
dataset: SST2
classifier: Bert
computer: labo
split: 1
dataset_size: 500
algo: GPT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 5
batch_size_classifier: 32
tokenizer: "tweetTokenizer"

num_epoch_algo: 20
batch_size_algo: 16
fix_dataset: False