---
dataset: IronyB
classifier: dummy
computer: labo
split: 1
dataset_size: 500
algo: ChatGPTDescriptionDummy
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 0
batch_size_classifier: 32

tokenizer: "tweetTokenizer"
fix_dataset: False