---
dataset: FakeNews
classifier: Bert
computer: labo
split: 10
dataset_size: 10
algo: BART
random_seed: 7
selector: random
max_seq_length: 0
one_shot: False
nb_epoch_classifier: 12
meta_strategy: dummy
batch_size_classifier: 32
tokenizer: "tweetTokenizer"

fix_dataset: True

batch_size_algo: 16
nb_epoch_algo: 4
learning_rate: 0.0005


batch_size_generation: 16