---
dataset: SST2
classifier: Bert
computer: labo
split: 5
dataset_size: 100
algo: T5BT
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 15
batch_size_classifier: 32
tokenizer: "tweetTokenizer"

batch_size_algo: 8
num_epoch_algo: 5
batch_size_generation: 8

#Whether to vary the dataset or not in the different training.
fix_dataset: True