---
dataset: FakeNews
classifier: Bert
computer: labo
split: 1
dataset_size: 0
algo: BART
random_seed: 7
selector: random
max_seq_length: 32
one_shot: False
meta_strategy: dummy
nb_epoch_classifier: 8

batch_size_classifier: 32
tokenizer: "tweetTokenizer"
batch_size_algo: 4
nb_epoch_algo: 4
learning_rate: 0.0005
batch_size_generation: 4

fix_dataset: False