---
dataset: TREC6
classifier: Bert
computer: labo
split: 0
dataset_size: 2000
algo: dummy
random_seed: 7
selector: random
max_seq_length: 0
one_shot: False
nb_epoch_classifier: 20
meta_strategy: dummy

batch_size_classifier: 32
fix_dataset: False
tokenizer: "tweetTokenizer"