---
dataset: TREC6
classifier: Bert
computer: labo
split: 0
dataset_size: 100
algo: dummy
random_seed: 7
selector: random
max_seq_length: 0
one_shot: False
meta_strategy: dummy
nb_epoch_classifier: 50

batch_size_classifier: 32
tokenizer: "tweetTokenizer"