---
dataset: TREC6
classifier: Bert
computer: labo
split: 5
dataset_size: 100
algo: T5ParQuora
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 50

batch_size_classifier: 32
tokenizer: "tweetTokenizer"
