---
dataset: SST2
classifier: Bert
computer: labo
split: 1
dataset_size: 1500
algo: VAE
random_seed: 7
selector: random
max_seq_length: 0
meta_strategy: dummy
one_shot: False
nb_epoch_classifier: 8

hidden_size_algo: 2048
word_dropout: 0.5
dropout_algo: 0.5
latent_size: 15
embeddings: None
freeze_embeddings: False
tie_embeddings: False
tie_encoders: True
nb_epoch_algo: 30
x0: 15
sampling_strategy: random